replicaCount: 1

image:
  repository: quay.io/lewagon/mlflow
  tag: latest
  pullPolicy: Always

dbConnectionString: "" # Set through shell or CI secrets
defaultArtifactRoot: "s3://lewagon-garage/mlflow-artifacts"

artifactStorage:
  endpoint: "https://ams3.digitaloceanspaces.com"
  key: ""
  secret: ""

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80
 
ingress:
  enabled: true
  annotations: 
    kubernetes.io/ingress.class: "traefik"
    certmanager.k8s.io/issuer: "letsencrypt-prod-issuer"
    certmanager.k8s.io/acme-challenge-type: "http01"
  tls: 
    - secretName: tls-cert
      hosts:
        - mlflow.lewagon.co
  hosts: 
    - mlflow.lewagon.co
  path: /

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# volumes:
#   - name: minio
#     persistentVolumeClaim:
#       claimName: minio

nodeSelector: {}

tolerations: []

affinity: {}
