apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: tls-cert
spec:
  secretName: tls-cert

  dnsNames:
    - mlflow.lewagon.co

  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
    group: cert-manager.io