{{ if and .Values.artifactStorage.key .Values.artifactStorage.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: spaces-credentials
  annotations:
    helm.sh/hook: pre-upgrade, pre-install
    helm.sh/hook-weight: "-2"
type: Opaque
stringData:
  artifact_storage_key: {{ .Values.artifactStorage.key }}
  artifact_storage_secret: {{ .Values.artifactStorage.secret }}
{{ end }}